name: sprout_mobile_developer_test
description: "Sprout Mobile Developer Test"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod_annotation: ^2.3.3
  fluttertoast: ^8.2.5
  provider: ^6.1.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  intl: ^0.19.0
  envied: ^0.5.3
  dio: ^5.4.3+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get: ^4.6.6
  get_server: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3

  # Riverpod
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:

  uses-material-design: true

